name_1 = input("Type a name: ")
adjective_1 = input("Type an adjective: ")
occupation_1 = input("Type an occupation: ")
name_2 = input("Type another name: ")
animal_1 = input("Type an animal: ")
name_3 = input("Type another name: ")
verb_1 = input("Type a verb: ")
animal_2 = input("Type another animal: ")
name_4 = input("Type another name: ")
adjective_2 = input("Type another adjective: ")
occupation_2 = input("Type another occupation: ")
verb_2 = input("Type another verb: ")
verb_3 = input("Type another verb: ")
verb_4 = input("Type another verb: ")
food_1 = input("Type a sort of food: ")

print("The Kingdom")
print("==================")
print("Once upon a time, " + name_1 + ", a " + adjective_1 + " " +
      occupation_1 + ",")
print("was put on a quest. The Kindgom of " + name_2 + " was ")
print("besieged by a vicious " + animal_1 + ", and required assistance.")
print(name_1 + " gained the aid of two helpers, " + name_3 + ", a ")
print(verb_1 + " " + animal_2 + ", and " + name_4 + ", a " + adjective_2 +
      " " + occupation_2 + ".")
print("Together, they " + verb_2 + " to " + name_2 + "'s aid and")
print(verb_3 + " off the vicious " + animal_1 + ". The day saved,")
print("they all " + verb_4 + " the victory, and ate " + food_1 + ".")
print("They all lived happily ever after.")
print("The end.")
